import os
import pandas as pd
import numpy as np
import datetime as dt

import dash
from dash import dcc, html, Input, Output
import plotly.express as px


def load_master_dataset():
    """Try several common locations for the master dataset and return a DataFrame.
    The function returns None if no file is found.
    """
    candidates = [
        "master_dataset_bmk.csv",
        os.path.join("data", "processed", "master_dataset_bmk.csv"),
    ]

    for p in candidates:
        if os.path.exists(p):
            try:
                df = pd.read_csv(p, parse_dates=["date"], index_col="date")
                return df
            except Exception as e:
                print(f"Error reading {p}: {e}")
                return None

    return None


df = load_master_dataset()

app = dash.Dash(__name__)
server = app.server

if df is None:
    app.layout = html.Div(
        [
            html.H2("Dataset introuvable"),
            html.P(
                "Aucun fichier `master_dataset_bmk.csv` trouvé. Placez le fichier à la racine du projet "
                "ou dans `data/processed/` puis relancez l'application."
            ),
        ],
        style={"fontFamily": "Arial", "margin": 40},
    )

else:
    # try to locate NDVI & SPI columns
    ndvi_col = next((c for c in ["ndvi_final", "ndvi_max_monthly", "ndvi"] if c in df.columns), None)
    spi3_col = next((c for c in ["spi_3", "spi3"] if c in df.columns), None)

    min_date = df.index.min().date()
    max_date = df.index.max().date()

    app.layout = html.Div(
        [
            html.H1("NDVI & SPI — Plotly Dash"),
            html.Div(
                [
                    html.Label("Période"),
                    dcc.DatePickerRange(
                        id="date-range",
                        min_date_allowed=min_date,
                        max_date_allowed=max_date,
                        start_date=min_date,
                        end_date=max_date,
                        display_format="YYYY-MM",
                    ),
                ],
                style={"marginBottom": 20},
            ),

            html.Div(id="metrics-row", style={"display": "flex", "gap": "40px", "marginBottom": 20}),

            dcc.Graph(id="ndvi-graph"),
            dcc.Graph(id="spi-graph"),

            html.Footer("Generated by app_dash.py — use `python app_dash.py` to run locally"),
        ],
        style={"maxWidth": 1200, "margin": "auto", "fontFamily": "Arial"},
    )


@app.callback(
    Output("ndvi-graph", "figure"),
    Output("spi-graph", "figure"),
    Output("metrics-row", "children"),
    Input("date-range", "start_date"),
    Input("date-range", "end_date"),
)
def update_charts(start_date, end_date):
    # Filter
    start = pd.to_datetime(start_date) if start_date else df.index.min()
    end = pd.to_datetime(end_date) if end_date else df.index.max()
    dff = df.loc[(df.index >= start) & (df.index <= end)].copy()

    metrics = []
    if ndvi_col in dff.columns:
        last_ndvi = dff[ndvi_col].dropna().iloc[-1] if not dff[ndvi_col].dropna().empty else np.nan
        metrics.append(html.Div([html.H4("Dernier NDVI"), html.P(f"{last_ndvi:.4f}")]))

    if spi3_col in dff.columns:
        last_spi3 = dff[spi3_col].dropna().iloc[-1] if not dff[spi3_col].dropna().empty else np.nan
        metrics.append(html.Div([html.H4("Dernier SPI-3"), html.P(f"{last_spi3:.3f}")]))

    # NDVI figure
    if ndvi_col and ndvi_col in dff.columns:
        fig_ndvi = px.line(dff, x=dff.index, y=ndvi_col, title="NDVI Time Series", labels={ndvi_col: "NDVI", "x": "Date"})
        fig_ndvi.update_traces(line=dict(color="#2ca02c"))
    else:
        fig_ndvi = px.line(title="NDVI: colonne introuvable")

    # SPI figure
    if spi3_col and spi3_col in dff.columns:
        fig_spi = px.line(dff, x=dff.index, y=spi3_col, title="SPI-3 Time Series", labels={spi3_col: "SPI-3", "x": "Date"})
        fig_spi.add_hline(y=0, line_dash="dash", line_color="gray")
        fig_spi.add_hline(y=-1.5, line_dash="dot", line_color="red")
    else:
        fig_spi = px.line(title="SPI: colonne introuvable")

    return fig_ndvi, fig_spi, metrics


if __name__ == "__main__":
    app.run_server(debug=True, port=8050)
